### ISSUE TITLE
Add dev user to seed

### ISSUE THREAD

**Issue by xander-miller** [BWieber/Blocitoff#7]
Adding a dev user, makes it easy to log back into the app if you have to reset the database. Add a user to the seed with the following attributes:
- [x] email is 'admin@example.com'
- [x] password is 'helloworld'

**Comment by BWieber** [comment]
Does PR #8 fix this?

**Comment by BWieber** [comment]
Hell noes! Keep trying.

**Comment by bran-van-d** [comment]
Dev added.
